// <auto-generated />
using System;
using LacVietGenealogy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LacVietGenealogy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902113229_AddMemberProfileFields")]
    partial class AddMemberProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.FamilyTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("JoinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("FamilyTrees");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.FamilyTreeMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LinkedMemberId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.HasIndex("LinkedMemberId");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("UserId", "FamilyTreeId")
                        .IsUnique();

                    b.ToTable("FamilyTreeMemberships");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Biography")
                        .HasColumnType("longtext");

                    b.Property<string>("BirthDateLunar")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BirthDateSolar")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("int");

                    b.Property<int?>("BirthLunarDay")
                        .HasColumnType("int");

                    b.Property<int?>("BirthLunarMonth")
                        .HasColumnType("int");

                    b.Property<int?>("BirthLunarYear")
                        .HasColumnType("int");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("int");

                    b.Property<int?>("BirthOrder")
                        .HasColumnType("int");

                    b.Property<string>("CourtesyName")
                        .HasColumnType("longtext");

                    b.Property<string>("CurrentResidence")
                        .HasColumnType("longtext");

                    b.Property<string>("DeathDateLunar")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeathDateSolar")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeathDay")
                        .HasColumnType("int");

                    b.Property<int?>("DeathLunarDay")
                        .HasColumnType("int");

                    b.Property<int?>("DeathLunarMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DeathLunarYear")
                        .HasColumnType("int");

                    b.Property<int?>("DeathMonth")
                        .HasColumnType("int");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GenerationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInLaw")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherNames")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("TabooName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.ParentChildRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ChildOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("FamilyTreeId");

                    b.HasIndex("ParentId");

                    b.ToTable("ParentChildRelationships");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RoleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.ToTable("RoleGroups");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RoleGroupPermission", b =>
                {
                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("RoleGroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RoleGroupPermissions");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SpouseRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HusbandId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MarriageOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("WifeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.HasIndex("HusbandId");

                    b.HasIndex("WifeId");

                    b.ToTable("SpouseRelationships");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SystemMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("SystemMenus");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SystemModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemModules");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.FamilyTree", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.FamilyTreeMembership", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.FamilyTree", "FamilyTree")
                        .WithMany()
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.Member", "LinkedMember")
                        .WithMany()
                        .HasForeignKey("LinkedMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LacVietGenealogy.Core.Entities.RoleGroup", "RoleGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyTree");

                    b.Navigation("LinkedMember");

                    b.Navigation("RoleGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.Member", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.FamilyTree", "FamilyTree")
                        .WithMany("Members")
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.ParentChildRelationship", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.Member", "Child")
                        .WithMany("ChildEdges")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.FamilyTree", "FamilyTree")
                        .WithMany()
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.Member", "Parent")
                        .WithMany("ParentEdges")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("FamilyTree");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.Permission", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.SystemMenu", "Menu")
                        .WithMany("Permissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RoleGroup", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.FamilyTree", "FamilyTree")
                        .WithMany()
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RoleGroupPermission", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.Permission", "Permission")
                        .WithMany("RoleGroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.RoleGroup", "RoleGroup")
                        .WithMany("RoleGroupPermissions")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("RoleGroup");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SpouseRelationship", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.FamilyTree", "FamilyTree")
                        .WithMany()
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.Member", "Husband")
                        .WithMany("HusbandEdges")
                        .HasForeignKey("HusbandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LacVietGenealogy.Core.Entities.Member", "Wife")
                        .WithMany("WifeEdges")
                        .HasForeignKey("WifeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilyTree");

                    b.Navigation("Husband");

                    b.Navigation("Wife");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SystemMenu", b =>
                {
                    b.HasOne("LacVietGenealogy.Core.Entities.SystemModule", "Module")
                        .WithMany("Menus")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.FamilyTree", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.Member", b =>
                {
                    b.Navigation("ChildEdges");

                    b.Navigation("HusbandEdges");

                    b.Navigation("ParentEdges");

                    b.Navigation("WifeEdges");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.Permission", b =>
                {
                    b.Navigation("RoleGroupPermissions");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.RoleGroup", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("RoleGroupPermissions");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SystemMenu", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.SystemModule", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("LacVietGenealogy.Core.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
